M48
; DRILL file {KiCad (6.0.7)} date Thu Oct 27 00:54:25 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-10-27T00:54:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X4.3064Y-1.4354
X4.3064Y-1.663
T2
X1.5748Y-1.4764
X1.5748Y-5.4134
X3.937Y-1.4764
X3.937Y-5.4134
T0
M30
